apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: app
    component: cart
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: app
      component: cart
  template:
    metadata:
      labels:
        project: roboshop
        tier: app
        component: cart
    spec:
      containers:
      - name: cart
        image: saikiranreddy11/cart:1.0.0
        envFrom:
        - configMapRef: 
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    component: cart
    tier: app
    project: roboshop
  ports:
  - name: cart-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"

