apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: app
    component: catalogue
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: app
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        tier: app
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: saikiranreddy11/catalogue:1.0.0
        envFrom:
        - configMapRef: 
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    component: catalogue
    tier: app
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO= "true"
  MONGO_URL= mongodb://mongodb:27017/catalogue

