apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: redis
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: redis
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: redis
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    tier: db
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis-port

